version: '3.7'

services:
  web:
    build:
      context: ./apache-php
      dockerfile: Dockerfile
    container_name: apache-php
    ports:
      - "80:80"
      - "8123:8123"    # Necesario para el VirtualHost por puerto
    volumes:
      - ./apache-php/www:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.7
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
      MYSQL_USER: prueba
      MYSQL_PASSWORD: prueba
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  db_data:
